### ISSUE TITLE
Private repo support

### ISSUE THREAD

**Issue by shreeyesh** [bunsenstraat/remix-storage-plugin#12]
Hey, I tried using dgit on my remix. I wanted to clone a private repo but was unable to do so, i tried looking it up on the net but was unable to find any reliable solution. Is it possible to clone a private repo?

**Comment by bunsenstraat** [comment]
yes you need to add a github token to the app. it's in the github part of the app.

first you need to get personal token from github - settings and give it repo access:

![Screenshot 2021-12-11 at 22 04 46](https://user-images.githubusercontent.com/2787300/145691610-2915bf1f-292b-449a-a597-a7fc17e8107f.png)

then in dgit

![Screenshot 2021-12-11 at 22 03 55](https://user-images.githubusercontent.com/2787300/145691582-48825731-f2de-409e-a2db-89ad9d7b7900.png)

hope that helps

**Comment by shreeyesh** [comment]
Yeah i did add the PAT earlier into config, it wasn't working then. Was saying repo not found. But am glad its working now ,maybe some issue with remix or browser,worked after restarting. Thanks.

**Comment by bunsenstraat** [comment]
please let me know if you run into anything, I haven't had much feedback on the plugin and I'd love to hear anything to make it better.
