### ISSUE TITLE
Can't clone Git repository - Error from IDE: DGIT is not allowed to call clone method of Decentralized git.

### ISSUE THREAD

**Issue by epomatti** [bunsenstraat/remix-storage-plugin#13]
Getting this error when trying to clone my public project:

> Error from IDE: DGIT is not allowed to call clone method of Decentralized git.

![image](https://user-images.githubusercontent.com/6530769/152646819-16e8e59d-04fe-42f7-9fa5-ac5900c276c2.png)

https://github.com/epomatti/full-blockchain-solidity

**Comment by wdphan** [comment]
im getting same issue, let me know if you fixed this :) thanks!

**Comment by bunsenstraat** [comment]
I fixed it. Please try again, you should get a permission popup from remix now. Let me know.
