### ISSUE TITLE
Cannot push project to git repo

### ISSUE THREAD

**Issue by snowyaya** [bunsenstraat/remix-storage-plugin#14]
Remix doesn't allow me to push the content to my github repo even if the remote branch was added successfully.
![image](https://user-images.githubusercontent.com/75382121/152695409-f0bf12a8-4da1-4113-b802-627ff51b26a4.png)

**Comment by bunsenstraat** [comment]
Ok let's connect and go through the steps to see what's wrong. @snowyaya

**Comment by snowyaya** [comment]
Hi!
Thanks for the response!
How should we go through this? I am very happy to help resolve the issue!

**Comment by bunsenstraat** [comment]
Hi, 
You can tell me the steps you made to get this error.

so on thing is to verify if both your local repo and remote are on the same branch
![Screenshot 2022-02-09 at 08 46 12](https://user-images.githubusercontent.com/2787300/153144931-950b17ac-cba8-4f54-b59b-7f5112c313a8.png)
