### ISSUE TITLE
cant connect to git

### ISSUE THREAD

**Issue by wdphan** [bunsenstraat/remix-storage-plugin#15]
wont connect to github and provides message:
error from IDE: DGIT is not allowed to call clone method of decentralized git

for some reason REMIX isnt connecting to github.

I initialize it like Remix tells me too and then it doesn't work...
this happens everytime I try to clone repository. very annoying please help thank you! :)

**Comment by bunsenstraat** [comment]
please try again, I've rolled out a fix. You should get a permission window now from remix to allow the import.

**Comment by wdphan** [comment]
it worked thank youi!!!
