### ISSUE TITLE
UI Issues with IndexDB addition

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-storage-plugin#16]
1. In cloning the Open Zeppelin repo -  dgit warns me about crashing the browser.  With IndexDB - its probably not necessary...but maybe.  It is nice to know the size of a repo.  But I am not sure it is needed to have the bar that shows how much room to go - if most repos will only have a small portion of that.
2. This image shows that the bar isn't so useful at 9mb.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/6050001/153655716-21a9607f-3f7a-4d16-871a-de0b97aa943a.png">

**Comment by bunsenstraat** [comment]
The modal is there for backwards compat with the non index remix as well as the bar
