### ISSUE TITLE
With multiple cloned repos should there be more than 1 remote?

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-storage-plugin#18]
I've cloned 2 Repos but I only see 1 option of a remote to erase.  So I added another remote and its there. But should there be a remote for every repo added?

**Comment by ryestew** [comment]
this happened on the IPFS link - but not when I running remix from localhost

**Comment by ryestew** [comment]
mmmm not so sure

**Comment by bunsenstraat** [comment]
No you can have multiple remotes for one repo. Just like in git cli. Origin etc.

**Comment by bunsenstraat** [comment]
Each time you clone you will get a new workspace with a remote. Adding remotes only makes sense if you want to push the current repo to another remote
