### ISSUE TITLE
general UI probs

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-storage-plugin#21]
Here's an image.  I was trying to understand what section I'm in and it took a while to figure out that I'm in the source control section.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/6050001/154406893-37f1c561-329e-43b3-9d79-215fd770bf78.png">

And also this image shows a few problems with the lack of contract in the selected accordion title as well as its indent - make is lose import
![digit-analysis1](https://user-images.githubusercontent.com/6050001/154407685-57d9aa4e-51b1-43e8-a42d-76c59e365f78.png)
ance.

**Comment by bunsenstraat** [comment]
What would you say is a good solution?

**Comment by bunsenstraat** [comment]
I can highlight the titles.

**Comment by bunsenstraat** [comment]
You mean indent right, not intent?

**Comment by bunsenstraat** [comment]
Indenting looses space. It's a problem.
