### ISSUE TITLE
I have been unable to push because of this error...

### ISSUE THREAD

**Issue by jnicdr** [bunsenstraat/remix-storage-plugin#24]
![error ide](https://user-images.githubusercontent.com/57753446/157813356-84ee1c96-03f3-4137-9ec2-2cc01fd4b875.png)

**Comment by jnicdr** [comment]
I get this error when i am trying to push into github

**Comment by jnicdr** [comment]
I get this error when i am trying to push into github

**Comment by bunsenstraat** [comment]
- do you have a github token set?
- did you set the correct REPO permissions on the token?

**Comment by ishon19** [comment]
I also had a similar issue due as I had not selected the repo rights while creating the personal access token, after doing so the pushes are working perfectly.

**Comment by osamarizk** [comment]
@ishon19 
could you please elaborate the steps of selection the right repo while creating the personal token

**Comment by ishon19** [comment]
@osamarizk Sure, when creating the personal access token (via settings > developer settings) on GH, select the **repo** checkbox as well along with **gist** as shown in the screenshot below. That should be it for being able to push. Hope this helps!

![image](https://user-images.githubusercontent.com/8505291/162599353-6103e748-5b61-4d1d-9538-62628f3c0c54.png)

**Comment by osamarizk** [comment]
@ishon19 
Thanks a lot
it works well now

**Comment by ishon19** [comment]
@osamarizk Happy to help :)
