### ISSUE TITLE
Commit gives the following error: Invalid checksum in Gitindex buffer

### ISSUE THREAD

**Issue by moonman369** [bunsenstraat/remix-storage-plugin#28]
Error: Invalid checksum in GitIndex buffer

I am getting this error when I am trying to commit changes.

**Comment by moonman369** [comment]
Error: Error from IDE : InternalError: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected efbfbdefbfbd7d676153276f2c4eefbfbdefbfbd but saw 9ff1a97ef395f357b48243dfa81397458cd4131a

**Comment by moonman369** [comment]
I am also getting

**Error**:  `Error from IDE: Failed to fetch`

When trying to push, pull or fetch

**Comment by bunsenstraat** [comment]
Should be fine now please test

**Comment by moonman369** [comment]
It is indeed fixed, sir. Thanks a lot.

**Comment by moonman369** [comment]
May I know what caused this particular problem? (Just out of curiosity)

**Comment by moonman369** [comment]
I am reopening this issue because I am facing the same problem while `commit` again.

**Comment by moonman369** [comment]
I am reopening this issue because I am facing the same problem when i am trying to `commit` , again.

**Comment by bunsenstraat** [comment]
@moonman369 Let's connect and see what the situation is and if I can reproduce the error in some way.

**Comment by moonman369** [comment]
I updated my browser. Seems to be working fine now, thank you.
