### ISSUE TITLE
Unpin parent pin

### ISSUE THREAD

**Issue by yann300** [bunsenstraat/remix-storage-plugin#4]
When a new commit is pinned to IPFS, maybe there should be an option to automatically unpin the previous pin ?

At the moment all the commits are pinned with different hashes, one can remove them one by one but that might not be ideal when there's a lot of pinned commits.
Another way would be to keep track of all the "parent" pins of a commit and to have a way to "Clear" (unpin) all of them manually but i a single action.

**Comment by bunsenstraat** [comment]
Good idea! I will figure something out.
