### ISSUE TITLE
DGIT plugin doesn't work

### ISSUE THREAD

**Issue by alchemist0404** [bunsenstraat/remix-storage-plugin#40]
I have installed DGIT plugin and I used to push my project to github. But after restarting my computer, I can not use DGIT plugin.

![image](https://user-images.githubusercontent.com/67555770/180169094-ef6d0911-d4b2-4f46-891f-6c8367b968eb.png)

Of course, I selected my correct workspace.
![image](https://user-images.githubusercontent.com/67555770/180169435-f7f5c127-1490-47a5-8a8f-23b9dab4aaa1.png)

I am getting this warning. How can I solve this issue?

**Comment by pixkk** [comment]
I have a same problem. Remix IDE 1.3.4.

**Comment by bunsenstraat** [comment]
Thanks guys. There is a bug! I will fix it.

**Comment by bunsenstraat** [comment]
please check if it works now. DGIT refreshes 3secs after the workspace changes.

**Comment by pixkk** [comment]
![image](https://user-images.githubusercontent.com/30828435/180650184-9e79db5f-bd5b-4408-b19f-a8e6d1c59d0d.png)
All works! Thx.

**Comment by bunsenstraat** [comment]
We will soon integrate DGIT into the remix monorepo, so any wishes or remarks are welcome.
