### ISSUE TITLE
Commit are always made with "Remix Workspace" name

### ISSUE THREAD

**Issue by Alekussu** [bunsenstraat/remix-storage-plugin#46]
Hello 

My commits are always done with the name "Remix workspace" and not with the name that i have indicates in the settings. Is it possible to modify the name for commit ? Thank you !
![image](https://user-images.githubusercontent.com/111154340/196007925-bd65ff17-434f-4ae0-912b-c1d622a35076.png)
![image](https://user-images.githubusercontent.com/111154340/196007879-de406ea9-12e2-4854-aec7-e1e3dffd468f.png)

**Comment by bunsenstraat** [comment]
Can you verify this bug with the current IDE? This was old behaviour.

**Comment by 0xheartcode** [comment]
This bug is ongoing with the current IDE.
My email is verified and my history is marked as Remix Workspace.
Please halp.
![image](https://user-images.githubusercontent.com/110746778/199218412-22803b27-b395-470b-bc03-922c9e677599.png)

![image](https://user-images.githubusercontent.com/110746778/199218284-a67d1944-a644-4800-b9bc-d9bad15d857a.png)

**Comment by bunsenstraat** [comment]
there is something wrong yes. I will make a fix.

**Comment by bunsenstraat** [comment]
should be fixed now, please test

**Comment by 0xheartcode** [comment]
Works perfectly, with "username" commit history.
For those reading, and having issues before: I generated a new API Key and recreated the project folder, cloned and then it worked.

**Comment by Alekussu** [comment]
I confirm that it is working now ! Note that the username defined in the settings is just use for commit history, on Github it will always be your account name

![image](https://user-images.githubusercontent.com/111154340/200766824-44615bdd-5f15-4d1f-b05a-462b2a510575.png)
![image](https://user-images.githubusercontent.com/111154340/200766785-cbf4fa67-f342-4969-a76c-73af14aab42f.png)

@0xheartcode I didn't need to do all this, it worked directly on my machine, but thanks for the explaination if someone have still the issue !
